mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('prms.urls')),
    path('admin/', admin.site.urls),
    #path('', include('django.contrib.auth.urls'))
]

mysite/prms/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('patient_create', views.patient_create, name='pcreate'),
    path('employee_create/<str:company_name>', views.employee_create, name='ecreate'),
    path('employee_list', views.employee_list, name='employees'),
    path('company_create', views.company_create, name='ccreate'),
    path('company_billing/<str:company_name>', views.company_billing, name='billing'),
    path('manager', views.manager, name='manager'),
    path('user', views.user, name='user'),
    path('practitioner', views.practitioner, name='practitioner'),
    path('calendar', views.calendar, name='calendar'),
    path('patient_list', views.patient_list, name='patient_list'),
    path('all_patients', views.all_patients, name='all_patients'),
    path('inventory', views.inventory, name='inventory'),
    path('dictionary', views.dictionary_list, name='dictionary'),
    path('d_more/<int:id>', views.d_more, name='d_more'),
    path('e_edit/<int:id>', views.e_edit, name='e_edit'),
    path('n_booking', views.new_booking, name='n_booking'),
    path('p_view/<int:id>', views.p_view, name='p_view'),
    path('new_visit/<int:id>', views.new_visit, name='new_visit'),
    path('edit_visit/<int:id>', views.edit_visit, name='edit_visit'),
    path('delete_visit/<int:id>', views.delete_visit, name='delete_visit'),
    path('add_med/<int:id>', views.add_med, name='add_med'),
    path('edit_med/<int:id>', views.edit_med, name='edit_med'),
]

mysite/prms/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import date


class Company(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    postal = models.IntegerField(default=0)
    employeesc = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class CompanyBilling(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    address = models.CharField(max_length=200)
    postal = models.IntegerField(default=0)
    amount = models.DecimalField(default=0, decimal_places=3, max_digits=6)
    outstanding = models.IntegerField(default=0)
    lastInvoice = models.DateField('Last Invoice')
    nextInvoice = models.DateField('Next Invoice')

    def __str__(self):
        return self.company


class Employees(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    #user = models.OneToOneField(User, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    groups = (("Manager", "Manager"),("Practitioner", "Practitioner"),("User", "User"))
    group = models.CharField(max_length=12, choices=groups, default="User")
    email = models.EmailField()
    phone = models.IntegerField(default=0000000000)
    password = models.CharField(max_length=200)

    def __str__(self):
        fullname = (f"{self.firstname} {self.surname}")
        return fullname


class Patients(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    email = models.EmailField()
    phone = models.IntegerField(default=0000000000)
    dob = models.DateField('Date of Birth',default=date.today)
    idNumber = models.CharField(max_length=13)
    address = models.CharField(max_length=200, default='JHB')
    medicalAid = models.BooleanField()
    maidName = models.CharField(max_length=25, blank=True, default='Basic')
    maidNumber = models.CharField(max_length=15, blank=True, default='0000')
    password = models.CharField(max_length=200)

    def __str__(self):
        fullname = (f"{self.firstname} {self.surname}")
        return fullname

class MedicalData(models.Model):
    patient = models.ForeignKey(Patients, on_delete=models.CASCADE)
    familyCancer = models.BooleanField(default=False)
    familyCancerNotes = models.CharField(max_length=500, blank=True,default='None')
    pastSurgery = models.BooleanField(default=False)
    pastSurgeryNotes = models.CharField(max_length=1000,blank=True,default='None')
    chronicIllness = models.BooleanField(default=False)
    chronicIllnessNotes = models.CharField(max_length=1000, blank=True,default='None')
    medication = models.CharField(max_length=1000, blank=True, default='None')
    otherNotes = models.CharField(max_length=1000, blank=True, default='None')
    files = models.FileField(blank=True)

    def __str__(self):
        return self.patient.__str__()

class DataDictionary(models.Model):
    item = models.CharField(max_length=200)
    definition = models.CharField(max_length=200)
    symptoms = models.CharField(max_length=200)
    recommendations = models.CharField(max_length=200)

class Bookings(models.Model):
    patient = models.ForeignKey(Patients, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Employees, on_delete=models.CASCADE)
    date = models.DateTimeField('Booking date&time')

class Visits(models.Model):
    patient = models.ForeignKey(Patients, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Employees, on_delete=models.CASCADE)
    date = models.DateTimeField('Visit date')
    reason = models.CharField(max_length=200)
    prognosis = models.CharField(max_length=1000)
    notes = models.CharField(max_length=1000, default="N/A", blank=True)
    perscription = models.BooleanField()
    files = models.FileField(blank=True)

    def __str__(self):
        return self.patient.__str__()

mysite/prms/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, redirect
from datetime import datetime, date
from django.contrib.auth.models import Group, User
from django.contrib.auth import login, authenticate, get_user_model, logout
from django.contrib.auth.decorators import login_required

from .forms import PatientForm, CompanyForm, EmployeeForm, CompanyBillingForm, LoginForm, BookingForm, VisitForm, MedForm
from .models import Patients, Company, Employees, DataDictionary, MedicalData, Visits
from django.contrib.auth.forms import UserCreationForm

comp = ""
User = get_user_model()


def index(request):
    template = loader.get_template('prms/index.html')
    return render(request, 'prms/index.html')


def login_view(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(request, username=username, password=password)
        if user != None:
            # user is valid and active -> is_active
            # request.user == user
            login(request, user)
            print(user.groups)
            if user.groups.filter(name='Manager').exists():
                return redirect('manager')
            elif user.groups.filter(name='User').exists():
                return redirect('user')
            else:
                return redirect('practitioner')
        else:
            # attempt = request.session.get("attempt") or 0
            # request.session['attempt'] = attempt + 1
            # return redirect("/invalid-password")
            request.session['invalid_user'] = 1 # 1 == True
    return render(request, "registration/login.html", {"form": form})

def logout_view(request):
    logout(request)
    return redirect('login')

def patient_create(request):
    form = EmployeeForm(request.POST or None)
    if form.is_valid():
        print('Saved')
        form.save()
        form = EmployeeForm()
    context = {'form': form}
    return render(request, 'prms/patient/create.html', context)

def company_create(request):
    form = CompanyForm(request.POST or None)
    if form.is_valid():
        comp = form.cleaned_data.get("name")
        form.save()
        return redirect(f'/company_billing/{comp}', company_name=comp)
    context = {'form': form}
    return render(request, 'prms/company/create.html', context)

def employee_create(request, company_name=""):
    form = EmployeeForm(request.POST or None)
    if company_name != "":
        compObj = Company.objects.get(name=company_name)
        form = EmployeeForm(request.POST or None, initial={'company': compObj, 'group': 'Manager'})
    if form.is_valid():
        print(form.cleaned_data.get("group"))
        user = User.objects.create_user(form.cleaned_data.get("email"), form.cleaned_data.get("email"), form.cleaned_data.get("password"))
        group = Group.objects.get(name=form.cleaned_data.get("group"))
        user.groups.add(group)
        form.save()
        form = EmployeeForm()
    context = {'form': form}
    return render(request, 'prms/employee/create.html', context)

def company_billing(request, company_name=""):
    form = CompanyBillingForm(request.POST or None)
    date = datetime.today().strftime('%Y-%m-20')
    if company_name != "":
        compObj = Company.objects.get(name=company_name)
        form = CompanyBillingForm(request.POST or None,
                              initial={'company': compObj,
                                         'address': compObj.address,
                                         'postal': compObj.postal,
                                         'lastInvoice': date,
                                         'nextInvoice': date})
    if form.is_valid():
        form.save()
        return redirect(f'/employee_create/{company_name}', company_name=comp)
    context = {'form': form}
    return render(request, 'prms/company/billing.html', context)

@login_required(login_url='login')
def manager(request):
    if not request.user.is_authenticated:
        return redirect('login')
    return render(request,'prms/dashboards/ManagerD.html')


def user(request):
    return render(request,'prms/dashboards/UserD.html')


def practitioner(request):
    return render(request,'prms/dashboards/PracD.html')


def calendar(request):
    return render(request,'prms/dashboards/calendar.html')


def patient_list(request):
    return render(request,'prms/dashboards/UserD.html')


def all_patients(request):
    user = Employees.objects.get(email=request.user.email)
    patients = Patients.objects.all().filter(company=user.company)
    context = {'patients': patients}
    return render(request, 'prms/patient/all_patients.html', context)


def inventory(request):
    return render(request,'prms/inventory/list.html')


def employee_list(request):
    user = Employees.objects.get(email=request.user.email)
    employees = Employees.objects.all().filter(company=user.company)
    context = {'employees': employees}
    return render(request,'prms/employee/employees.html', context)

def dictionary_list(request):
    return render(request,'prms/dictionary/list.html')

def d_more(request, id):
    data = DataDictionary.objects.get(pk=id)
    context = {'data': data}
    return render(request,'prms/dictionary/more.html', context)

def e_edit(request, id):
    data = Employees.objects.get(pk=id)
    context = {'data': data}
    return render(request,'prms/employees/edit.html', context)

def new_booking(request):
    user = Employees.objects.get(email=request.user.email)
    employees = Employees.objects.all().filter(company=user.company)
    doctors = Employees.objects.all().filter(company=user.company, group='Practitioner')
    patients = Patients.objects.all().filter(company=user.company)
    filter = {'doctor': doctors, 'patient': patients}
    print(doctors, patients)

    form = BookingForm(request.POST or None, initial=filter)
    if form.is_valid():
        form.save()
        form = EmployeeForm()
    context = {'employees': employees, 'doctors': doctors, 'form': form}
    return render(request,'prms/bookings/new.html', context)

def p_view(request, id):
    patient = Patients.objects.get(pk=id)
    visit = Visits.objects.all().filter(patient=patient).order_by('-date')
    last = Visits.objects.all().filter(patient=patient).latest('date')
    medData = ""
    try:
        medData = MedicalData.objects.get(patient=patient)
        context = {'patient': patient, "visits": visit, 'last': last, "medData": medData}
        print(medData)
    except:
        context = {'patient': patient, "visits": visit, 'last': last, "medData": False}

    print("med data", medData)
    return render(request,'prms/patient/view.html', context)

def new_visit(request, id):
    user = Employees.objects.get(email=request.user.email)
    patients = Patients.objects.get(pk=id)
    filter = {'doctor': user, 'patient': patients, 'date': datetime.now()}

    form = VisitForm(request.POST or None, initial=filter)
    if form.is_valid():
        print("Valid")
        form.save()
        return redirect(f'/p_view/{id}')
    elif request.POST:
        print("Invalid", form.cleaned_data.get("doctor"))
    context = {'employees': user, 'patient': patients, 'form': form}
    return render(request, 'prms/visits/Add.html', context)

def edit_visit(request, id):
    data = Visits.objects.get(pk=id)
    patients = data.patient
    filter = {'doctor': request.user,
              'patient': patients,
              'date': data.date,
              'reason': data.reason,
              'prognosis': data.prognosis,
              'notes': data.notes,
              'perscription': data.perscription}
    form = VisitForm(request.POST or None, initial=filter)
    if form.is_valid():
        data.date = form.cleaned_data.get('date')
        data.reason = form.cleaned_data.get('reason')
        data.prognosis = form.cleaned_data.get('prognosis')
        data.notes = form.cleaned_data.get('notes')
        data.perscription = form.cleaned_data.get('perscription')

        data.save()
        return redirect(f'/p_view/{data.patient.id}')
    context = {'data': data, 'form': form}
    return render(request,'prms/visits/edit.html', context)

def delete_visit(request, id):
    user = Employees.objects.get(email=request.user.email)
    Visits.objects.filter(pk=id).delete()
    return redirect(f'/p_view/{user.pk}')

def edit_med(request, id):
    user = Employees.objects.get(email=request.user.email)
    patient = Patients.objects.get(pk=id)
    form = MedForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = EmployeeForm()
    context = {'patient': patient, 'form': form}
    return render(request, 'prms/med-data/edit.html', context)

def add_med(request, id):
    user = Employees.objects.get(email=request.user.email)
    patient = Patients.objects.get(pk=id)
    filter = {'patient': patient}
    form = MedForm(request.POST or None, initial=filter)
    if form.is_valid():
        form.save()
        return redirect(f'/p_view/{id}')
    else:
        print('invalid')
    context = {'patient': patient, 'form': form}
    return render(request, 'prms/med-data/add.html', context)

mysite/prms/templates/prms/visits/Add.html
{% extends 'prms/dashboards/base.html' %}
{% load static %}
<html lang="en">

<!-- MAIN CONTENT-->
{% block content%}
<head>
    <title>New visit</title>
</head>
<div class="containter-fluid">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <form method="post">
                {% csrf_token %}
                <div class="card-header">
                <strong>New appointment</strong>
            </div>
            <div class="card-body card-block">
                {{form.doctor}}
                {{form.patient}}
             <div class="form-group">
                <label  class=" form-control-label">Date</label>
                 <br>
                 {{form.date}}
             </div>
            <div class="form-group">
                <label  class=" form-control-label">Reason for visit</label>
                <textarea name="reason" id="id_reason" rows="9" placeholder="Reason for visit..." class="form-control" required></textarea>
            </div>
            <div class="form-group">
                <label class=" form-control-label">Prognosis</label>
                <textarea name="prognosis" id="id_prognosis" rows="9" placeholder="Content..." class="form-control" required></textarea>
            </div>
            <div class="form-group">
                <label class=" form-control-label">Prescription</label>
                {{form.perscription}}
            </div>
            <div class="form-group">
                <label class=" form-control-label">Notes</label>
                <textarea name="notes" id="id_notes" rows="9" placeholder="Additional notes if required..." class="form-control"></textarea>
            </div>
            <div class="form-group">
                <label class=" form-control-label">Files</label><br>
                {{form.files}}
            </div>
                <button type="submit" class="btn btn-primary btn-sm">
                    <i class="fa fa-dot-circle-o"></i> Submit
                </button>
            </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

</html>
<!-- end document-->

mysite/prms/templates/prms/visits/Edit.html
{% extends 'prms/dashboards/base.html' %}
{% load static %}
<html lang="en">

<!-- MAIN CONTENT-->
{% block content%}
<head>
    <title>Edit visit</title>
</head>
<div class="containter-fluid">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <form method="post">
                {% csrf_token %}
                <div class="card-header">
                <strong>Edit appointment from {{ data.date }}</strong>
            </div>
            <div class="card-body card-block">
                {{form.doctor}}
                {{form.patient}}
             <div class="form-group">
                <label  class=" form-control-label">Date</label>
                 <br>
                 {{form.date}}
             </div>
            <div class="form-group">
                <label  class=" form-control-label">Reason for visit</label>
                <textarea name="reason" id="id_reason" rows="9" placeholder="Reason for visit..." class="form-control" required>
                    {{data.reason}}
                </textarea>
            </div>

            <div class="form-group">
                <label class=" form-control-label">Prognosis</label>
                <textarea name="prognosis" id="id_prognosis" rows="9" placeholder="Content..." class="form-control" required>
                    {{data.prognosis}}
                </textarea>
            </div>
            <div class="form-group">
                <label class=" form-control-label">Prescription</label>
                {{form.perscription}}
            </div>
            <div class="form-group">
                <label class=" form-control-label">Notes</label>
                <textarea name="notes" id="id_notes" rows="9" placeholder="Additional notes if required..." class="form-control">
                    {{data.notes}}
                </textarea>
            </div>
            <div class="form-group">
                <label class=" form-control-label">Files</label><br>
                {{form.files}}
            </div>
                <button type="submit" class="btn btn-primary btn-sm">
                    <i class="fa fa-dot-circle-o"></i> Submit
                </button>
            </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

</html>
<!-- end document-->

mysite/prms/templates/prms/visits/View.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>